spring:
  application:
    name: training-provider
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
server:
  error:
    include-message: always
